In [1]:
import pandas as pd

In [29]:
datos = pd.read_csv('India_Menu.csv')

In [31]:
datos.head(10)

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168 g,402.05,10.24,13.83,5.34,0.16,2.49,56.54,7.90,4.49,706.13
1,Regular Menu,McAloo Tikki Burger®,146 g,339.52,8.50,11.31,4.27,0.20,1.47,50.27,7.05,4.07,545.34
2,Regular Menu,McSpicy™ Paneer Burger,199 g,652.76,20.29,39.45,17.12,0.18,21.85,52.33,8.35,5.27,1074.58
3,Regular Menu,Spicy Paneer Wrap,250 g,674.68,20.96,39.10,19.73,0.26,40.93,59.27,3.50,1.08,1087.46
4,Regular Menu,American Veg Burger,177 g,512.17,15.30,23.45,10.51,0.17,25.24,56.96,7.85,4.76,1051.24
5,Regular Menu,Veg Maharaja Mac,306 g,832.67,24.17,37.94,16.83,0.28,36.19,93.84,11.52,6.92,1529.22
6,Regular Menu,Green Chilli Aloo Naan,132 g,356.09,7.91,15.08,6.11,0.24,9.45,46.36,4.53,1.15,579.60
7,Regular Menu,Pizza Puff,87 g,228.21,5.45,11.44,5.72,0.09,5.17,24.79,2.73,0.35,390.74
8,Regular Menu,Mc chicken Burger,173 g,400.80,15.66,15.70,5.47,0.16,31.17,47.98,5.53,4.49,766.33
9,Regular Menu,FILLET-O-FISH Burger,136 g,348.11,15.44,14.16,5.79,0.21,32.83,38.85,5.58,3.54,530.54

In [32]:
datos.tail(20)

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
121,Beverages Menu,Small Thums-up,299 ml,99.60,0.00,0.00,0.00,0.00,0.00,24.90,24.90,24.90,25.15
122,Beverages Menu,Medium Thums-up,394 ml,137.60,0.00,0.00,0.00,0.00,0.00,34.40,34.40,34.40,34.74
123,Beverages Menu,Large Thums-up,544 ml,197.60,0.00,0.00,0.00,0.00,0.00,49.40,49.40,49.40,49.89
124,Beverages Menu,Small Sprite,299 ml,119.52,0.00,0.00,0.00,0.00,0.00,29.88,29.88,29.88,2.02
125,Beverages Menu,Medium Sprite,394 ml,165.12,0.00,0.00,0.00,0.00,0.00,41.28,41.28,41.28,2.79
126,Beverages Menu,Large Sprite,544 ml,237.12,0.00,0.00,0.00,0.00,0.00,59.28,59.28,59.28,4.00
127,Beverages Menu,Coke Float,286.79 ml,138.76,1.52,1.75,1.28,0.05,4.70,29.22,28.23,24.54,44.53
128,Beverages Menu,Fanta Float,286.79 ml,151.56,1.52,1.75,1.28,0.05,4.70,32.42,31.43,27.74,66.61
129,Beverages Menu,Sprite Float,286.79 ml,145.16,1.52,1.75,1.28,0.05,4.70,30.82,29.83,26.14,47.09
130,Beverages Menu,Coke Zero Can,330 ml,0.99,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,24.75
131,Beverages Menu,Vedica Natural Mineral Water,500 ml,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.90
132,Condiments Menu,Mustard diping sauce,25 g,81.18,0.52,5.57,1.78,0.47,0.29,7.24,6.66,4.00,221.32
133,Condiments Menu,BBQ diping sauce,25 g,54.89,0.26,0.49,0.15,0.04,0.25,12.36,7.65,2.50,113.23
134,Condiments Menu,Chilli Sauce,10 g,8.07,0.03,0.01,0.01,0.01,0.10,1.99,1.53,1.34,65.24
135,Condiments Menu,Piri Piri Mix,5 g,17.13,0.51,0.36,0.08,0.01,0.05,2.50,0.66,0.40,414.71
136,Condiments Menu,Tomato Ketchup Sachets,8 g,11.23,0.08,23.45,0.00,0.01,0.08,2.63,2.33,1.64,71.05
137,Condiments Menu,Maple Syrup,30 g,86.40,0.00,0.00,0.00,0.00,0.30,21.60,16.20,5.34,15.00
138,Condiments Menu,Cheese Slice,14 g,51.03,3.06,3.99,2.89,0.01,13.43,0.72,0.54,0.00,178.95
139,Condiments Menu,Sweet Corn,40 g,45.08,1.47,1.00,0.22,0.04,2.00,7.55,2.54,0.00,0.04
140,Condiments Menu,Mixed Fruit Beverage,180 ml,72.25,0.65,0.02,0.02,0.02,0.01,18.00,16.83,0.00,10.80

In [33]:
df1 = pd.DataFrame(datos)

In [34]:
df1

,Menu Category,Menu Items,Per Serve Size,Energy (kCal),Protein (g),Total fat (g),Sat Fat (g),Trans fat (g),Cholesterols (mg),Total carbohydrate (g),Total Sugars (g),Added Sugars (g),Sodium (mg)
0,Regular Menu,McVeggie™ Burger,168 g,402.05,10.24,13.83,5.34,0.16,2.49,56.54,7.90,4.49,706.13
1,Regular Menu,McAloo Tikki Burger®,146 g,339.52,8.50,11.31,4.27,0.20,1.47,50.27,7.05,4.07,545.34
2,Regular Menu,McSpicy™ Paneer Burger,199 g,652.76,20.29,39.45,17.12,0.18,21.85,52.33,8.35,5.27,1074.58
3,Regular Menu,Spicy Paneer Wrap,250 g,674.68,20.96,39.10,19.73,0.26,40.93,59.27,3.50,1.08,1087.46
4,Regular Menu,American Veg Burger,177 g,512.17,15.30,23.45,10.51,0.17,25.24,56.96,7.85,4.76,1051.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Condiments Menu,Tomato Ketchup Sachets,8 g,11.23,0.08,23.45,0.00,0.01,0.08,2.63,2.33,1.64,71.05
137,Condiments Menu,Maple Syrup,30 g,86.40,0.00,0.00,0.00,0.00,0.30,21.60,16.20,5.34,15.00
138,Condiments Menu,Cheese Slice,14 g,51.03,3.06,3.99,2.89,0.01,13.43,0.72,0.54,0.00,178.95
139,Condiments Menu,Sweet Corn,40 g,45.08,1.47,1.00,0.22,0.04,2.00,7.55,2.54,0.00,0.04
140,Condiments Menu,Mixed Fruit Beverage,180 ml,72.25,0.65,0.02,0.02,0.02,0.01,18.00,16.83,0.00,10.80

In [35]:
Datos = df1['Menu Category']=="Regular Menu"

In [36]:
print (Datos)

0       True
1       True
2       True
3       True
4       True
       ...
136    False
137    False
138    False
139    False
140    False
Name: Menu Category, Length: 141, dtype: bool

In [37]:
datos.shape

(141, 13)

In [38]:
datos.size

1833

In [40]:
datos['Menu Category'].head(15)

0     Regular Menu
1     Regular Menu
2     Regular Menu
3     Regular Menu
4     Regular Menu
5     Regular Menu
6     Regular Menu
7     Regular Menu
8     Regular Menu
9     Regular Menu
10    Regular Menu
11    Regular Menu
12    Regular Menu
13    Regular Menu
14    Regular Menu
Name: Menu Category, dtype: object